name: orca:npm:ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: npm install, build, and test
        run: |
          npm i
          npm run bootstrap
          npm run lint
          npm run dist
      - name: run security audit of npm packages
        run: |
          npm run audit-ci
      - name: scan for exposed aws secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd ./git-secrets
          sudo make install
          cd ../
          rm -rf git-secrets
          git secrets --register-aws
          git-secrets --scan -r
      - name: publish packages where the latest version is not present in the registry
        run: |
          npm run publish:package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish updated packages to npm registry with canary tag
        run: |
          npm run publish:canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
